### ISSUE TITLE
Question: Labels of auto-annotate

### ISSUE THREAD

**Issue by nyxrobotics** [pieterblok/maskal#12]
Hello,
I am trying to customize this software for my own project.
I am trying to create a dataset with two labels, "person" and "roboone".
<details>
  <summary>maskal.yaml</summary>

  ```yaml
# training-parameters
classes: ['person', 'roboone']
# train-sampler
minority_classes: ['person', 'roboone']
# folders
weightsroot: "/home/nyx/lib/roboone_auto_dataset/maskal_ws/weights"
resultsroot: "/home/nyx/lib/roboone_auto_dataset/maskal_ws/results"
dataroot: "/home/nyx/lib/roboone_auto_dataset/maskal_ws/datasets"
initial_train_dir: "/home/nyx/lib/roboone_auto_dataset/maskal_ws/datasets/initial_train"
traindir: "/home/nyx/lib/roboone_auto_dataset/maskal_ws/datasets/train"
valdir: "/home/nyx/lib/roboone_auto_dataset/maskal_ws/datasets/val"
testdir: "/home/nyx/lib/roboone_auto_dataset/maskal_ws/datasets/test"
# data options
use_initial_train_dir: False
duplicate_initial_model_and_data: False
initial_train_file: ""
# active-learning sampling
supervisely_meta_json: "/home/nyx/lib/roboone_auto_dataset/maskal_ws/datasets/meta.json"
# training-parameters
cuda_visible_devices: '0'
transfer_learning_on_previous_models: True
learning_rate: 0.01
warmup_iterations: 500
train_iterations_base: 2500
train_iterations_step_size: 2500
step_image_number: 500
eval_period: 500
checkpoint_period: -1
weight_decay: 0.0001
learning_policy: 'steps_with_decay'
step_ratios: [0.5, 0.8]
gamma: 0.1
train_batch_size: 1
num_workers: 2
# train-sampler
train_sampler: "TrainingSampler"
repeat_factor_smallest_class: 1.0
# evaluation-parameters
confidence_threshold: 0.5
nms_threshold: 0.2
# active-learning sampling
experiment_name: 'exp1'
strategy: 'uncertainty'
mode: 'mean'
initial_datasize: 5
pool_size: 5
equal_pool_size: True
loops: 5
dropout_probability: 0.25
mcd_iterations: 10
iou_thres: 0.5
auto_annotate: True
export_format: labelme
### Light-weight
network_config: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
pretrained_weights: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
  ```
</details>

After the first auto-annotation, the labelme will look like the following image.
![Screenshot from 2023-06-26 18-50-57](https://github.com/pieterblok/maskal/assets/19720932/86325a9d-a021-4863-91e0-2a43a1ba6fcf)

What I would like to do is the following
- When the Enter key is pressed,
  - Datasets with labels (bottle, skis, cup, motorcycle, chair) that are not included in `classes` are assumed to have errors and left in the annotate directory.
  - If a polygon extends outside of the image, it is deformed to fit inside the image.

Which files should be changed to implement these features?
